### ISSUE TITLE
Made Some Modifications as Novelai Was Not Working in Risu's Node Version

### ISSUE THREAD

**Issue by poroyo** [kwaroran/RisuAI#236]
Hello. I am a user who has been using Risu's node version quite well. When I tried to use Novelai in the risu node version, the app was terminated with a Json parsing error.

So, I made a few modifications to the `server/node/server.cjs` file, and I was able to receive a normal response.

1. I changed the 45th line to `const urlParam = req.headers['risu-url'] ? decodeURIComponent(req.headers['risu-url']) : req.query.url;`
2. I changed the 71st line to `const head = new Headers(originalResponse.headers);`
3. And then,
```
    const headObj = {};
    for (let [k, v] of head) {
        headObj[k] = v;
    }
    res.header(headObj);
```
I created an object like this and put it into header.

Doing so, Novelai now works well in the risu node version, but I am posting this in case there might be additional problems or mistakes in the code I modified.

Thank you.

**Comment by SeA-luby** [comment]
I am also getting this horrible error. Could you provide any further clarification on the modifications you made? The line 45 modification obviously fixes the JSON.parse error, but I don't quite understand the rest of the process.

**Comment by SeA-luby** [comment]
Hello, the conclusion I came to last night was the same as the one you just described above. I also did some research on my own and tentatively determined the cause of it as:

> The `TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["append"]`, is being caused by the line res.header(head) because the `res.header()` method is not a standard method provided by Express.
> To set headers in the response using Express, I should use the res.set() or res.header() method. However, the code is trying to pass a HeadersList object directly, which is not compatible with these methods.

To resolve this issue I needed to convert the HeadersList object into a regular JavaScript object before passing it to res.set() or res.header(). I could do this by iterating through the HeadersList object and constructing a plain JavaScript object with the header names and values, which means you were ultimately right anyway. XD

Except that in my case, I had to enable Force Plain Fetch to get a proper response. Perhaps something is slightly missing in the parsing process, but I'm too lazy to check the response body format again for exact troubleshooting hehe

What's interesting is that this issue was already raised at least 2 months ago, which is unfortunate because he hasn't updated server.cjs since 3 months ago. Hopefully he will pay attention to the node version too and fix this issue soon. Your raising the issue was very helpful. Best regards.
