### ISSUE TITLE
[Feature Request] Global lorebook feature request to save settings including name of {{User}}

### ISSUE THREAD

**Issue by Hanydabal** [kwaroran/RisuAI#35]
Background: There is no global information about {{User}}, so there is a need to organize information about {{User}}, which is relatively non-intuitively delivered to AI, due to the tendency to be separately entered in the lower book / artist's note / character prompt. .

Purpose: “Global User Lorebook” allows users to set up two or more {{User}} Lorebooks (similar to character cards), so that when you use one of them on a talking AI, it will automatically {{User}} Make settings for {User}} easier to understand

Features I want:

- “Global User Lorebook”: A prompt system in the form of a Global Lorebook that is supported similarly to a character card. The purpose is to include the profile picture of {{User}}, so that you can select one of them when starting a conversation.

- Additional support within the “Character Card 2.0” form: Certain characters may be set to deal with {{User}} in a specific setting. Expanding the concept of overriding front-end ones when setting some system prompts in “Character Card 2.0”. By providing a more regular and formal area, just setting up a character card supports card creators and users changing and saving the settings of {{User}} they want.

**Comment by Alwaysfindtheway** [comment]
I agree and recommend adding this feature.

Also, when the character card 2 version is launched, it would be nice to have a separate field to fill in the user's information.

Or, even if that's not possible, it would be nice to be able to specify a character for {{user}} in the User Settings panel, separate from the Lorebook/World Info feature, so that we can use {{char}} when needed. character bot card, and swap out a small token amount of {{user}} character bot card for a small amount of tokens when needed.
---
저도 이 의견에 동의하며, 해당 기능의 추가를 지지합니다.

또한 캐릭터 카드 2 버전이 도입될 때, 유저의 정보를 따로 기입하는 칸이 있으면 좋겠습니다.

또는, 그게 아니더라도 로어북/월드 인포 기능과 별도로 User 설정 창에서 {{user}}의 캐릭터를 지정하여 필요할 때 {{char}} 캐릭터 봇 카드를 스왑하듯, 적은 토큰양의 {{user}} 캐릭터 봇 카드를 스왑하여 이용할 수 있으면 더욱 재밌고 편리할 것 같습니다.

**Comment by kwaroran** [comment]
Done in current version
